// try-catch catches the exception
import System;

int x = 10, y = 20;
try {
	throw new Exception("message");
	y = 140;
} catch (Exception ex) {
	x = 70;
}