try {
	f();	
} catch (Exception e1) {
	g();
} finally {
	h();
}