try {
	f();
} catch (Exception1 e1) {
	g1();
}